stages:
  - plan
  - apply
  - docker-push
  - deploy
  - ansible

variables:
  TF_ROOT: "terraform"

image:
  name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  entrypoint: [""]

# template
.cd_root_and_init:
  before_script:
    - cd $TF_ROOT
    - terraform init -backend-config="bucket=$TF_STATE_S3_BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
  
terraform-plan:
  stage: plan
  rules:
    # - when: never # working but disabled
  extends:
    - .cd_root_and_init
  script:
    - mkdir build
    - terraform plan

  artifacts:
    paths:
      - build/
  allow_failure: false


terraform-apply:
  stage: apply
  dependencies:
    - terraform-plan
  rules:
    # - when: never # working but disabled
  extends:
    - .cd_root_and_init
  script:
    - terraform apply -auto-approve
    # - terraform apply -auto-approve -destroy

    # update CI/CD env var with the new IP for other jobs to use
    - EC2_PUBLIC_IP=$(terraform output -raw zeelz_db_ec2_ip) #terraform output -json > tf-outputs.json # needs jq
    - echo $EC2_PUBLIC_IP > key # for other jobs

    - |
      curl -X PUT \
        --form "value=$EC2_PUBLIC_IP" \
        --header "Authorization: Bearer $GITLAB_PAT_TOKEN" \
        "https://gitlab.com/api/v4/projects/74663565/variables/ZEELZ_EC2_IP"

    # Send EC2 IP to Slack
    - |
      curl -X POST \
        --header "Content-Type: application/json" \
        -d "{\"text\": \"ZEELZ_EC2_IP: $EC2_PUBLIC_IP\"}" \
        $SLACK_WEBHOOK_URL

# ansible0:
#   stage: ansible
#   dependencies:
#     - terraform-apply
#   before_script:
#     - mkdir -p ~/.ssh
#     - echo "$SSH_PRIVATE_KEY" > ~/.ssh/key.pem
#     - chmod 600 ~/.ssh/key.pem
#     - apk add --no-cache ansible openssh

#   script:
#     - sleep 30
#     - cd ansible
#     - echo "[app]" > inventory.ini
#     - echo "server ansible_host=$(cat ../ec2_ip.txt) ansible_user=ubuntu ansible_ssh_private_key_file=key.pem" >> inventory.ini
#     - ansible all -i inventory.ini -m wait_for_connection
#     - ansible-playbook -i inventory.ini playbook.yml

ansible:
  image: willhallonline/ansible:latest
  stage: ansible
  dependencies:
    - terraform-apply
  script:
    # Create inventory file
    - echo "[ec2]" > inventory.ini
    - EC2_PUBLIC_IP=$(cat $TF_ROOT/key)
    - echo "$EC2_PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=$SSH_PRIVATE_KEY" >> inventory.ini
    - chmod 600 $SSH_PRIVATE_KEY # rw- for the key file
    # Run Ansible playbook
    - ansible-playbook -i inventory.ini ansible/playbook.yml


    
docker-build-push:
  stage: docker-push
  image: docker:24
  services:
    - docker:24-dind
  rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: never
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: ""
  dependencies: []

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin

  script:
    # - cat build/dummy
    - docker build -t $DOCKER_USER/express-gitlab -f Dockerfile.gitlab .
    - docker push $DOCKER_USER/express-gitlab

# deploy-to-ec2:
#   image: alpine
#   stage: deploy
#   needs: [docker-build-push]
#   rules:
#     # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#     # - when: never # working but disabled for now
#   script:
#     - chmod +x ssh-install-deploy.sh
#     - ./gitlab-ssh-install-deploy.sh
