stages:
 - oidc-test

sts-caller:
 stage: oidc-test
 image:
  name: "amazon/aws-cli"
  entrypoint: [""]
 id_tokens:
  AWS_ID_TOKEN:
    aud: sts.amazonaws.com
 script:
  - mkdir -p ~/.aws
  - printf "%s" "$AWS_ID_TOKEN" > /tmp/web_identity_token
  - |
    cat > ~/.aws/config <<EOF
    [profile oidc]
    role_arn=${OIDC_ROLE_ARN}
    web_identity_token_file=/tmp/web_identity_token
    EOF
  - aws sts get-caller-identity --profile oidc

