stages:
 - oidc-test

before_script:
  - mkdir -p ~/.aws
  - echo "${CI_JOB_JWT_V2}" > /tmp/web_identity_token
  - |
    cat <<EOF > ~/.aws/config
    [profile oidc]
    role_arn=${OIDC_ROLE_ARN}
    web_identity_token_file=/tmp/web_identity_token
    EOF

sts-caller:
 stage: oidc-test
 image:
  name: "amazon/aws-cli"
  entrypoint: [""]
 script:
  - aws sts get-caller-identity --profile oidc

