FROM node:alpine

WORKDIR app/

COPY package.json .

COPY package-lock.json .

RUN npm ci

COPY db.ts .

COPY index.ts .

COPY index.local.ts .

COPY tsconfig.json .

RUN npm run build

CMD ["node", "build/index.local.js"]