FROM node:alpine

WORKDIR /app

# COPY package.json package-lock.json ./
COPY package*.json ./

RUN npm ci

COPY db.ts index.ts index.local.ts tsconfig.json ./

RUN npm run build

CMD ["node", "build/index.local.js"]