---
- name: create file play
  hosts: webserver
  become: true
  vars:
    appdir: wacrm

  tasks:
    - name: update cache
      ansible.builtin.apt:
        update_cache: yes

    - name: install git and curl
      apt:
        name: [git, curl]
        state: present

    - name: download node.js installer
      shell:
        cmd: curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - 
        creates: /etc/apt/sources.list.d/nodesource.list

    - name: install nodejs
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: clone repo
      git:
        repo: https://github.com/ArnasDon/wacrm.git
        dest: "{{ appdir }}"

    - name: copy env
      copy:
        src: .env.local
        dest: "{{ appdir }}"

    - name: npm install
      community.general.npm:
        path: /home/ubuntu/wacrm #install pkgs from package.json

    - name: install pm2
      community.general.npm:
        name: pm2
        global: true

    - name: npm run dev
      shell:
        cmd: pm2 start npm --name wacrm-app -- run dev
        chdir: "{{ appdir }}"