name: "Setup and Start Wacrm App"

on:
  push

  # workflow_run:
  #   workflows: ["Provision and deploy"]

jobs:
  setup-start-wacrm:
    runs-on: ubuntu-latest
    env:
      EC2_IP: ${{ secrets.EC2_IP }}

    steps:
    # Check out your repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Install Ansible natively using pip
    - name: Install Ansible
      run: |
        python3 -m pip install --upgrade pip
        pip install ansible

    # Setup SSH keys securely for authentication to targeted remote hosts
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}

    - name: try ssh
      run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${EC2_IP} "echo connected"

    # Execute the playbook
    # - name: Run Ansible Playbook
    #   run: |
    #     cd ansible
    #     ansible-playbook -i inventory \
    #     --ssh-extra-args="-o StrictHostKeyChecking=no" \
    #     --extra-vars "ansible_host=${EC2_IP}" \
    #     --extra-vars "ansible_user=ubuntu" \
    #     playbook.yml       
