name: "Setup and Start Wacrm App"

on:
  push

  # workflow_run:
  #   workflows: ["Provision and deploy"]
  #   types: [completed]

jobs:
  setup-start-wacrm:
    runs-on: ubuntu-latest

    steps:
    # Check out your repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Download artifact from provsioner workflow
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: ip-file-uploader # now ip-var.txt is availble to use in steps
    #     run-id: ${{ github.event.workflow_run.id }}
    #     github-token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Inject values from file into env vars
    #   id: env-injector
    #   run: |
    #     while IFS= read -r $line; do
    #       echo "$line" >> $GITHUB_OUTPUT
    #     done < ${{ github.workspace }}/ip-var.txt

    # Install Ansible natively using pip
    - name: Install Ansible
      run: |
        python3 -m pip install --upgrade pip
        pip install ansible

    # Setup SSH keys securely for authentication to targeted remote hosts
    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}

    # Execute the playbook
    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory \
        --extra-vars "ansible_host=${{ secrets.EC2_IP }}" \
        --extra-vars "ansible_user=ubuntu" \
        playbook.yml       


      # --extra-vars "ansible_host=${{ steps.env-injestor.outputs.EC2_IP }}" \

      # curl -X POST --header "Content-Type: application/json" -d "{\"text\": \"EC2 IP: $EC2_IP\"}" \
      # ${{ vars.SLACK_WEBHOOK_URL }}