name: Deploy App Runner service

on:
    push:
      branches: [dev]        

jobs:
    apprunner_deploy:
        runs-on: ubuntu-latest

        env:
            REGION: "us-east-1"

        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: Configure AWS Credentials # not needed for tf, just passed those cred as env vars
              uses: aws-actions/configure-aws-credentials@v5.0.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.REGION }}

            - name: App Runner Deploy
              id: deploy-apprunner
              uses: awslabs/amazon-app-runner-deploy@main # Deploy app runner service
              with:
                service: express-app-3-github-action
                source-connection-arn: ${{ secrets.AWS_GITHUB_CONNECTION_ARN }}
                repo: https://github.com/${{ github.repository }}
                branch: ${{ github.ref }}
                runtime: NODEJS_22
                build-command: npm install
                start-command: node build/index.js
                port: 18000
                region: ${{ env.REGION }}
                cpu : 1
                memory : "500Mi"
                wait-for-service-stability-seconds: 600
                instance-role-arn: ${{ secrets.APPRUNNER_INSTANCE_ROLE }}