name: "Build Push nodejs"

on:
    push:
      branches: [dev__DISABLED]

jobs:
    build-push:
        if: true #you can also use this to disble job true/false
        runs-on: ubuntu-latest
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            
    # defaults:
        #     run:
        #         shell: bash
        #         working-directory: "app"
        steps:
            - name: checkout
              uses: actions/checkout@v4
              
            - name: Get commit sha
              run: |
                export SHORT_SHA="${GITHUB_SHA::7}"
                echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"
                echo "$SHORT_SHA" > "${{ github.workspace }}/github-sha.txt"

            - name: Upload github sha
              uses: actions/upload-artifact@v4
              with:
                name: github-sha
                path: ${{ github.workspace }}/github-sha.txt

            - name: npm install
              run: npm ci

            - name: setup docker
              uses: docker/setup-docker-action@v4

            - name: docker build
              run: docker build -t ${DOCKER_USER}"/express-containerized":${{ env.SHORT_SHA }} .

            - name: docker login
              run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

            - name: docker push
              run: docker push ${DOCKER_USER}"/express-containerized:${{ env.SHORT_SHA }}"