name: Deploy to Kubernetes

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

jobs:
  deploy_app:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: "5b8c780" # ${GITHUB_SHA::7}
      CLUSTER_NAME: "eks-cluster-08"
      AWS_REGION: "us-east-1"

    steps:
      - name: checkout
        uses: actions/checkout@v5

      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}

      - name: Update Kubeconfig
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }}

      # - name: Add Cluster Access entry and policy
      #   run: |
      #     aws eks create-access-entry \
      #     --cluster-name ${{ env.CLUSTER_NAME }} \
      #     --principal-arn ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }} \
      #     --type STANDARD

      #     aws eks associate-access-policy \
      #     --cluster-name ${{ env.CLUSTER_NAME }} \
      #     --principal-arn ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }} \
      #     --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy \
      #     --access-scope type=cluster

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Helm install release
        run: |
          helm upgrade --install express-containerized ./helm/express-containerized \
          --values ./helm/express-containerized/values.yaml \
          --set image.tag=${{ env.IMAGE_TAG }}